### ISSUE TITLE
Ignored failure when legalizing block ops

### ISSUE THREAD

**Issue by dcaballe** [tensorflow/mlir#43] opened 2019-07-09 00:44 UTC
Hi!

We recently updated the version of MLIR that we are using for our nGraph dialect and noticed that the rewriter now has checks wrt legality of generated operations in the context of the destination dialect. This is great! It uncovered that we were generating an unsupported operation during the nGraph->affine lowering. However, root-causing the problem was a bit tricky since the `applyConversionPatterns` API didn’t return a failure and our compiler crashed far down the road. I found out that `OperationLegalizer::legalize` returned failure but this is ignored by the caller: https://github.com/tensorflow/mlir/blob/master/lib/Transforms/DialectConversion.cpp#L911

Is this an expected behavior? If so, would it make sense to have a stricter path/mode that propagates the failure to the caller instead?

Thanks!
Diego

**Comment by River707** [comment] 2019-07-09 16:47
Hi!
Yes that is currently the expected behavior, as it is intended to make partial conversions easier. That being said, as you have discovered, this is not always the desired behavior. I have plans for two additional flavors of legalization:
* Full conversion (I think this is the one you want)
  - If the legalization of any operations fail, the entire conversion fails.
* Analysis conversion
  - Check to see which operations *would* be legalized if the conversion was applied, but don't actually apply the conversion.

I've been mainly focused on turning Functions/Modules into operations the past twoish weeks, but I should be able get to these sometime this week.

-- River

**Comment by dcaballe** [comment] 2019-07-09 22:00
> * Full conversion (I think this is the one you want)
>   * If the legalization of any operations fail, the entire conversion fails.

Yes, this is it. Please, let us know if you see any opportunity for us to help. We would be happy to do so :)

Thanks!
Diego

**Comment by River707** [comment] 2019-07-16 21:06
This should be fixed by [97b4684](https://github.com/tensorflow/mlir/commit/97b468490d45437d9aa9a7a3f85e0651bb40c260).

**Closed** 2019-07-17 19:14 UTC

**Comment by dcaballe** [comment] 2019-07-17 21:52
Thanks!
